#!/bin/bash

#| Report the current state of the elasticsearch cluster.
# Of most interest is the 'metadata' section, to determine whether or not any index
# templates are defined.
# The more indices that exist, the longer this report will get.

# -----------------------------------------
# Setup, common to all scripts here
# -----------------------------------------
pushd `dirname $0` > /dev/null
source usage
source options; options $*
result=$?
popd > /dev/null

if [ "$result" != "0" ]
then
  # We did not pass the basic parameter validation.
  usage
  exit 1
fi
# -----------------------------------------

echo
curl -s -XGET "$elastic/_cluster/state?pretty=true"
echo
echo

